### ISSUE TITLE
Stackblitz can't run the showcase application

### ISSUE THREAD

**Issue by TapaiBalazs** [thisdot/open-source#94]
IF you open the repository in stackblitz, the start command does not start up the showcase application. Investigate if the same issue happens locally. If not, then investigate what can go wrong in stackblitz.

**Comment by TapaiBalazs** [comment]
When I import the project, this is the output I get. It says that the NX Daemon is not running.

```
~/projects/qgniylalb.github
❯ npm install && npm start
warn preInstall No description field
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 0.317s
┌ [2/4] 🚚  Fetching dependencies
│ info pruneDeps Excluding 25 dependencies. For more information use `--verbose`.
└ Completed in 2.1s
┌ [3/4] 🔗  Linking dependencies
└ Completed in 1.57s
info security We found `install` scripts which turbo skips for security reasons. For more information see
https://turbo.sh/install-scripts.
├─ @nrwl/angular@14.3.5
├─ nx@14.3.6
├─ @parcel/watcher@2.0.4
├─ core-js@3.23.1
├─ core-js-pure@3.23.1
├─ cypress@8.7.0
├─ esbuild@0.14.38
├─ esbuild@0.14.11
└─ nx@14.3.5
info Some packages were automatically replaced with polyfills. For more information see https://turbo.sh/polyfills.
├─ esbuild@0.14.38 => esbuild-wasm@0.14.38
└─ esbuild@0.14.11 => esbuild-wasm@0.14.11
$ node ./decorate-angular-cli.js && ngcc --properties es2020 browser module main

 >  NX   Angular CLI has been decorated to enable computation caching.


success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 6.446s
$ nx serve showcase
nx run [project][:target][:configuration] [_..]

Run a target for a project
(e.g., nx run myapp:serve:production).

You can also use the infix notation to run a target:
(e.g., nx serve myapp --configuration=production)

You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version           Show version number                                                                      [boolean]
      --prod              Use the production configuration                                        [boolean] [default: false]
  -c, --configuration     Target configuration                                                                      [string]
      --project           Target project                                                                            [string]
      --output-style      Defines how Nx emits outputs tasks logs
                                     [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes", "compact"]
      --nx-bail           Stop command execution after the first failed task                      [boolean] [default: false]
      --nx-ignore-cycles  Ignore cycles in the task graph                                         [boolean] [default: false]

Error: The Daemon Server is not running
Messages from the log:



More information: /home/projects/qgniylalb.github/node_modules/.cache/nx/d/daemon.log
    at daemonProcessException (/home/projects/qgniylalb.github/node_modules/nx/src/daemon/client/client.js:66:16)
    at Socket.eval (/home/projects/qgniylalb.github/node_modules/nx/src/daemon/client/client.js:148:29)
    at EventEmitter.emit (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:6:155573)
    at emitErrorNT (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:6:367810)
    at emitErrorCloseNT (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:6:367457)
    at _0x2b9b99 (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:15:130586)
    at https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:15:130343
```

**Comment by TapaiBalazs** [comment]
So I noticed a pattern that it runs for people who are based in Africa, but it does not run for people based in Europe.
Based on that I created this issue at the webcontainer repository:

https://github.com/stackblitz/webcontainer-core/issues/735
